import time, os, colorama, pathlib

from colorama import Fore, Back, Style

from pathlib import Path
from os import environ, getcwd

colorama.init()
print(colorama.Fore.GREEN +   '''   1. Alan Walker - Alone
   2. Alan Walker - Sing Me to Sleep
   3. Alan Walker AAP Rocky - Live_Fast
   4. Alan Walker Imanbek - Sweet Dreams
   5. Alan Walker, ISK - Sorry''')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   6. CHVRCHS - Miracle')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   7. Clandestina')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   8. Eminem - Rap God')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   9. Eva Simons - Bludfire')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   10. Hans Zimmer - End Credits')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   11. Katy Perry, Juicy J - Dark_Horse')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   12. Alan Walker - Legends Never Die')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   13. Leonid Rudenko, ARITMIYA - Rain Sun')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   14. Minelli - Rampampam')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   15. Ness Barrett jxdn - la di die')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   16. Parah Dice - Hot')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   17. Steve Aoki, Alan Walker, Isak - Are You Lonely')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   18. TOMYGONE Amvi s - What More')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   19. Oxxxymiron - Цунами') # всё начиная с 19 - скачать
time.sleep(0.05)
print(colorama.Fore.YELLOW + '   20. Annodomini - Никто не нужен')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   21. AC/DC - War machine')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   22. AC/DC - T.N.T')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   23. AC/DC - Thunderstruck')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   24. AC/DC - Highway to Hell')
time.sleep(0.05)
print(colorama.Fore.YELLOW + '   25. AC/DC - Back in Black')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   26. GHOSTEMANE - Fed Up')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   27. GHOSTEMANE - Venom')
time.sleep(0.05)
print(colorama.Fore.RED + '   28. $UICEDEBOY$ - LTE')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   29. $UICEDEBOY$ - Paris')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   30. Lil Peep - Star Shopping')
time.sleep(0.05)
print(colorama.Fore.YELLOW + '   31. Король и Шут - Лесник')
time.sleep(0.05)
print(colorama.Fore.RED + '   32. Lost Frequencies - Reality')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   33. The Score - Head Up')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   34. DISTURBED - Old Friend')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   35. Король и Шут - Кукла колдуна')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   36. БИ-2, oxxxymiron - Пора возвращаться домой') #дописать
time.sleep(0.05)
print(colorama.Fore.GREEN + '   37. Blues Saraceno - Dogs of War')
time.sleep(0.05)
print(colorama.Fore.YELLOW + '   38. БИ-2 - Большие города')
time.sleep(0.05)
print(colorama.Fore.RED + '   39. Thousand Foot Krutch - Take It Out Me')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   40. Skillet - Back to Life')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   41. K.Flay - High Enough')
time.sleep(0.05)
print(colorama.Fore.RED + '   42. Three Days Grace - So Called Life')
time.sleep(0.05)
print(colorama.Fore.YELLOW + '   43. Chvrches, Matt Berninger - My Enemy')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   44. Bishop Briggs - River')
time.sleep(0.05)
print(colorama.Fore.YELLOW + '   45. Disturbed - Liberate')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   46. Oxxxymiron, Porchy - Earth Burns')
time.sleep(0.05)
print(colorama.Fore.GREEN + '   47. Papa Roach - Last Resort')
time.sleep(0.05)
print(colorama.Fore.WHITE +  '   48. Slipknot - Dead Memories')
time.sleep(0.05)
print(colorama.Fore.YELLOW + '   49. Dope - Die MF Die')
time.sleep(0.05)
print(colorama.Fore.GREEN +  '   50. Slipknot - Before I Forget')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   51. Александр Пушной - Всё идёт по плану')
time.sleep(0.05)
print(colorama.Fore.WHITE + '   52. Би-2 - Чёрное солнце')
time.sleep(0.05)
print(colorama.Fore.GREEN+ '\n       Плейлист с oxxxymiron:')
time.sleep(2)
print(colorama.Fore.CYAN + '   53. Oxxxymiron - В книге всё было по-другому (4 раунд, 17ib)' )
time.sleep(0.05)
print(colorama.Fore.CYAN + '   54. Oxxxymiron - Дело нескольких минут (3 раунд, 17 ib)')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   55. Oxxxymiron, Самариддин Раджабов - Ветер перемен (2 раунд 17ib)')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   56. Oxxxymiron - В долгий путь (1 раунд 17ib)')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   57. Oxxxymiron - До зимы')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   58. Oxxxymiron - Не от мира сего')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   59. Oxxxymiron - Признаки жизни')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   60. Oxxxymiron - Детектор лжи')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   61. Oxxxymiron - Хитиновый покров')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   62. Oxxxymiron - Волапюк')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   63. Oxxxymiron - Больше Бена')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   64. Oxxxymiron - Цифры и цвета')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   65. Oxxxymiron - Где нас нет')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   66. Oxxxymiron - Башня из слоновой кости')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   67. Oxxxymiron - Слово мэра')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   68. Oxxxymiron - Накануне')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   69. Oxxxymiron - Полигон')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   70. Oxxxymiron - Колыбельная')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   71. Oxxxymiron - Переплетено')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   72. Oxxxymiron - Всего лишь писатель')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   73. Oxxxymiron - Кем ты стал')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   74. Oxxxymiron - Город под подошвой')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   75. Oxxxymiron ft. пиэм ft. J. Makonnen ft. Dinast ft. Letai ft. PALMDROPOV - Reality')
time.sleep(0.05)
print(colorama.Fore.CYAN + '   76. Oxxxymiron, Markul - Fata Morgana')
time.sleep(0.05)
print(Style.RESET_ALL)
print()



